/// @filename FeatureMeter.h
/// @brief InstantSonicView feature meters manager
/// @author gm
/// @copyright gm 2014
///
/// This file is part of InstantSonicView
///
/// InstantSonicView is free software: you can redistribute it and/or modify
/// it under the terms of the GNU General Public License as published by
/// the Free Software Foundation, either version 3 of the License, or
/// (at your option) any later version.
///
/// InstantSonicView is distributed in the hope that it will be useful,
/// but WITHOUT ANY WARRANTY; without even the implied warranty of
/// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
/// GNU General Public License for more details.
///
/// You should have received a copy of the GNU General Public License
/// along with InstantSonicView.  If not, see <http://www.gnu.org/licenses/>.


// This file is NOT generated by Juce (at least not after the first time),
// That's why we apply our coding style here


#ifndef INSTANTSONICVIEW_IMPLEMENTATION_COMMON_FEATUREMETER_H_
#define INSTANTSONICVIEW_IMPLEMENTATION_COMMON_FEATUREMETER_H_

#include "JuceHeader.h"

#include "instantsonicview/src/analyzer/feature_meta.h"
#include "instantsonicview/implementation/common/Meter.h"

// Using declarations for InstantSonicView features
using instantsonicview::analyzer::FeatureMeta;

/// @brief Feature meters manager
///
/// This component bridges the gap between InstantSonicView features management
/// and UI stuff such as meters displaying the features actual value
class FeatureMeter : public MeterComponent {
 public:
  explicit FeatureMeter(const FeatureMeta& meta);
  ~FeatureMeter();

  void paint(juce::Graphics& g);

 private:
  juce::DrawableText label_;
};

#endif  // INSTANTSONICVIEW_IMPLEMENTATION_COMMON_FEATUREMETER_H_
