/// @filename FeatureMeter.cpp
/// @brief InstantSonicView feature meters manager - implementation
/// @author gm
/// @copyright gm 2014
///
/// This file is part of InstantSonicView
///
/// InstantSonicView is free software: you can redistribute it and/or modify
/// it under the terms of the GNU General Public License as published by
/// the Free Software Foundation, either version 3 of the License, or
/// (at your option) any later version.
///
/// InstantSonicView is distributed in the hope that it will be useful,
/// but WITHOUT ANY WARRANTY; without even the implied warranty of
/// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
/// GNU General Public License for more details.
///
/// You should have received a copy of the GNU General Public License
/// along with InstantSonicView.  If not, see <http://www.gnu.org/licenses/>.


// This file is NOT generated by Juce (at least not after the first time),
// That's why we apply our coding style here

#include "instantsonicview/implementation/common/FeatureMeter.h"

FeatureMeter::FeatureMeter(const FeatureMeta& meta)
    : MeterComponent(MeterType::MeterVertical),
      label_() {
  label_.setText(juce::String(meta.name()));
  addAndMakeVisible(&label_);
}

FeatureMeter::~FeatureMeter() {
  // Nothing to do here for now
}

void FeatureMeter::paint(juce::Graphics& g) {
  label_.setCentreRelative(0.5f, 0.95f);
  label_.setColour(juce::Colours::whitesmoke);
  MeterComponent::paint(g);
}
